version: '3'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    command: mosquitto
  mondog:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
      - /data/configdb:/data/configdb
  telegr:
    build:
      context: ~/atom/electron
    depends_on:
      - mondog

